DX              = pi/para.DWNkmax;
xmax            = DX*para.DWNnbptkx/2;
DK              = para.DWNkmax/(para.DWNnbptkx*pi);
strinfoDWN      = {['DX=',num2str(DX,2)];...
                   ['Xmax=',num2str(xmax,2)];...
%                    ['DK=',num2str(DK,2)];...
                   ['L=',num2str(2*pi/DK,2)]};
set(info.infoDWN,'string',strinfoDWN);
